# Generated by Django 4.1.3 on 2022-12-16 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0005_userprofile_first_name_userprofile_last_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="connections",
            old_name="connection_profile",
            new_name="connection_profile_id",
        ),
        migrations.RenameField(
            model_name="connections",
            old_name="user_profile",
            new_name="user_profile_id",
        ),
    ]
