# Generated by Django 4.1.3 on 2022-12-16 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "user_profile",
            "0006_rename_connection_profile_connections_connection_profile_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_email_notifications_active", models.BooleanField(default=True)),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("professional", "professional"),
                            ("classic", "classic"),
                        ],
                        default="professional",
                        max_length=15,
                    ),
                ),
                ("theme_color", models.CharField(default="#023458", max_length=7)),
                (
                    "user_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Analytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile_views",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                (
                    "saved_contacts",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                (
                    "exchanged_contacts",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                (
                    "user_profile_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_profile.userprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
