# Generated by Django 4.1.3 on 2022-12-16 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0007_usersettings_analytics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_profile.userprofile",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="analytics",
            name="exchanged_contacts",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="analytics",
            name="profile_views",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="analytics",
            name="saved_contacts",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="analytics",
            name="user_profile_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="user_profile.userprofile",
            ),
        ),
        migrations.CreateModel(
            name="SharedDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("contact_number", models.CharField(max_length=15)),
                (
                    "profile_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_profile.userprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
