# Generated by Django 4.1.3 on 2022-12-19 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0009_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="links",
            name="provider",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_profile.providers",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="links",
            name="url",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="providers",
            name="icon",
            field=models.ImageField(upload_to="icons"),
        ),
    ]
