# Generated by Django 4.1.3 on 2022-12-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0012_remove_connections_connection_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_url",
            field=models.URLField(),
        ),
    ]
