# Generated by Django 4.1.3 on 2022-12-20 10:44

from django.db import migrations, models

import user_profile.validators


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0014_userprofile_email_userprofile_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="address",
            field=models.JSONField(
                default=list, validators=[user_profile.validators.validate_website]
            ),
        ),
        migrations.DeleteModel(
            name="Address",
        ),
    ]
