# Generated by Django 4.1.3 on 2022-12-22 04:31

from django.db import migrations, models
import user_profile.validators


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0015_userprofile_address_delete_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="address",
            field=models.JSONField(
                default=list, validators=[user_profile.validators.validate_address]
            ),
        ),
    ]
