# Generated by Django 4.1.3 on 2022-12-22 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0016_alter_userprofile_address"),
        ("user_profile", "0016_alter_userprofile_address_card"),
    ]

    operations = []
