# Generated by Django 4.1.3 on 2022-12-22 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0017_connections_unique contact email_and_more"),
        ("user_profile", "0017_merge_20221222_0433"),
    ]

    operations = []
