# Generated by Django 4.1.3 on 2022-12-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0018_merge_20221222_0746"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
