# Generated by Django 4.1.3 on 2022-12-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0021_alter_card_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providers",
            name="icon",
            field=models.ImageField(unique=True, upload_to="icons"),
        ),
        migrations.AlterField(
            model_name="providers",
            name="title",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
