# Generated by Django 4.1.3 on 2022-12-28 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0022_alter_providers_icon_alter_providers_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="user_profile.userprofile",
            ),
        ),
    ]
