# Generated by Django 4.1.3 on 2023-02-14 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0027_alter_analytics_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analytics",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="user_profile.userprofile",
            ),
        ),
    ]
