# Generated by Django 4.1.3 on 2023-02-16 04:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0029_alter_analytics_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providers",
            name="icon",
            field=models.FileField(
                upload_to="icons",
                validators=[
                    django.core.validators.FileExtensionValidator(["jpg", "png", "svg"])
                ],
            ),
        ),
    ]
