# Generated by Django 4.1.3 on 2023-02-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0030_alter_providers_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="countrycode",
            name="country",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
