# Generated by Django 4.1.7 on 2023-02-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0032_auto_20230216_0932"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_source",
            field=models.CharField(
                choices=[("youtube", "youtube"), ("vimeo", "vimeo")],
                default="youtube",
                max_length=15,
            ),
        ),
    ]
