# Generated by Django 4.1.7 on 2023-02-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0033_alter_video_video_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="analytics",
            name="ip_address",
            field=models.GenericIPAddressField(default="127.0.0.1"),
            preserve_default=False,
        ),
    ]
