
# Generated by Django 4.1.7 on 2023-02-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0034_analytics_ip_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="printed",
            field=models.BooleanField(default=False),
        ),
    ]
