# Generated by Django 4.1.7 on 2023-02-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0035_card_printed"),
    ]

    def new_ids(apps, schema_editor):
        card_model = apps.get_model("user_profile", "Card")
        cards = card_model.objects.all()
        for i, card_obj in enumerate(cards, 1):
            card_obj.card_serial_no = i
            card_obj.save()

    operations = [
        migrations.AddField(
            model_name="card",
            name="card_serial_no",
            field=models.IntegerField(
                auto_created=True, default=1, verbose_name="card_serial_no"
            ),
        ),
        migrations.RunPython(new_ids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="card",
            name="card_serial_no",
            field=models.IntegerField(
                editable=False, null=True, unique=True, verbose_name="card_serial_no"
            ),
        ),
    ]
