# Generated by Django 4.1.7 on 2023-03-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0037_card_assigned"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
