# Generated by Django 4.1.7 on 2023-03-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0038_card_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="connections",
            name="company_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
