# Generated by Django 4.1.7 on 2023-04-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0041_auto_20230410_0958"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="label",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
