# Generated by Django 4.1.3 on 2023-04-27 11:16

from django.db import migrations


def insert_link_postion(apps, schema_editor):
    profile_model = apps.get_model("user_profile", "UserProfile")
    profile_card_model = apps.get_model("user_profile", "ProfileCards")
    data = [
        {"name": "about me", "position": 1},
        {"name": "review links", "position": 2},
        {"name": "social links", "position": 3},
        {"name": "website links", "position": 4},
        {"name": "videos", "position": 5},
        {"name": "contact information", "position": 6},
    ]
    profile_data = profile_model.objects.all()
    for profile in profile_data:
        new_card = profile_card_model(profile=profile, data=data)
        new_card.save()


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0042_profilecards"),
    ]

    operations = [
        migrations.RunPython(
            insert_link_postion, reverse_code=migrations.RunPython.noop
        )
    ]
