# Generated by Django 4.1.3 on 2023-01-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_invitationcode_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitationcode",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
