country_json = [
    {
        "id": 1,
        "name": "Afghanistan",
        "country_code": "93",
        "iso_code": "AF",
        "whatsapp_price": 0.08,
    },
    {
        "id": 2,
        "name": "Albania",
        "country_code": "355",
        "iso_code": "AL",
        "whatsapp_price": 0.09,
    },
    {
        "id": 3,
        "name": "Algeria",
        "country_code": "213",
        "iso_code": "DZ",
        "whatsapp_price": 0.09,
    },
    {
        "id": 4,
        "name": "American Samoa",
        "country_code": "1684",
        "iso_code": "AS",
        "whatsapp_price": 0.06,
    },
    {
        "id": 5,
        "name": "Andorra",
        "country_code": "376",
        "iso_code": "AD",
        "whatsapp_price": 0.06,
    },
    {
        "id": 6,
        "name": "Angola",
        "country_code": "244",
        "iso_code": "AO",
        "whatsapp_price": 0.09,
    },
    {
        "id": 7,
        "name": "Anguilla",
        "country_code": "1264",
        "iso_code": "AI",
        "whatsapp_price": 0.06,
    },
    {
        "id": 8,
        "name": "Antarctica",
        "country_code": "672",
        "iso_code": "AQ",
        "whatsapp_price": 0.06,
    },
    {
        "id": 9,
        "name": "Antigua and Barbuda",
        "country_code": "1268",
        "iso_code": "AG",
        "whatsapp_price": 0.06,
    },
    {
        "id": 10,
        "name": "Argentina",
        "country_code": "54",
        "iso_code": "AR",
        "whatsapp_price": 0.07,
    },
    {
        "id": 11,
        "name": "Armenia",
        "country_code": "374",
        "iso_code": "AM",
        "whatsapp_price": 0.09,
    },
    {
        "id": 12,
        "name": "Aruba",
        "country_code": "297",
        "iso_code": "AW",
        "whatsapp_price": 0.06,
    },
    {
        "id": 13,
        "name": "Australia",
        "country_code": "61",
        "iso_code": "AU",
        "whatsapp_price": 0.08,
    },
    {
        "id": 14,
        "name": "Austria",
        "country_code": "43",
        "iso_code": "AT",
        "whatsapp_price": 0.11,
    },
    {
        "id": 15,
        "name": "Azerbaijan",
        "country_code": "994",
        "iso_code": "AZ",
        "whatsapp_price": 0.09,
    },
    {
        "id": 16,
        "name": "Bahamas",
        "country_code": "1242",
        "iso_code": "BS",
        "whatsapp_price": 0.06,
    },
    {
        "id": 17,
        "name": "Bahrain",
        "country_code": "973",
        "iso_code": "BH",
        "whatsapp_price": 0.08,
    },
    {
        "id": 18,
        "name": "Bangladesh",
        "country_code": "880",
        "iso_code": "BD",
        "whatsapp_price": 0.08,
    },
    {
        "id": 19,
        "name": "Barbados",
        "country_code": "1246",
        "iso_code": "BB",
        "whatsapp_price": 0.06,
    },
    {
        "id": 20,
        "name": "Belarus",
        "country_code": "375",
        "iso_code": "BY",
        "whatsapp_price": 0.09,
    },
    {
        "id": 21,
        "name": "Belgium",
        "country_code": "32",
        "iso_code": "BE",
        "whatsapp_price": 0.11,
    },
    {
        "id": 22,
        "name": "Belize",
        "country_code": "501",
        "iso_code": "BZ",
        "whatsapp_price": 0.06,
    },
    {
        "id": 23,
        "name": "Benin",
        "country_code": "229",
        "iso_code": "BJ",
        "whatsapp_price": 0.09,
    },
    {
        "id": 24,
        "name": "Bermuda",
        "country_code": "1441",
        "iso_code": "BM",
        "whatsapp_price": 0.06,
    },
    {
        "id": 25,
        "name": "Bhutan",
        "country_code": "975",
        "iso_code": "BT",
        "whatsapp_price": 0.06,
    },
    {
        "id": 26,
        "name": "Bolivia",
        "country_code": "591",
        "iso_code": "BO",
        "whatsapp_price": 0.08,
    },
    {
        "id": 27,
        "name": "Bosnia and Herzegovina",
        "country_code": "387",
        "iso_code": "BA",
        "whatsapp_price": 0.06,
    },
    {
        "id": 28,
        "name": "Botswana",
        "country_code": "267",
        "iso_code": "BW",
        "whatsapp_price": 0.09,
    },
    {
        "id": 29,
        "name": "Brazil",
        "country_code": "55",
        "iso_code": "BR",
        "whatsapp_price": 0.08,
    },
    {
        "id": 30,
        "name": "British Indian Ocean Territory",
        "country_code": "246",
        "iso_code": "IO",
        "whatsapp_price": 0.06,
    },
    {
        "id": 31,
        "name": "British Virgin Islands",
        "country_code": "1284",
        "iso_code": "VG",
        "whatsapp_price": 0.06,
    },
    {
        "id": 32,
        "name": "Brunei",
        "country_code": "673",
        "iso_code": "BN",
        "whatsapp_price": 0.06,
    },
    {
        "id": 33,
        "name": "Bulgaria",
        "country_code": "359",
        "iso_code": "BG",
        "whatsapp_price": 0.09,
    },
    {
        "id": 34,
        "name": "Burkina Faso",
        "country_code": "226",
        "iso_code": "BF",
        "whatsapp_price": 0.09,
    },
    {
        "id": 35,
        "name": "Burundi",
        "country_code": "257",
        "iso_code": "BI",
        "whatsapp_price": 0.09,
    },
    {
        "id": 36,
        "name": "Cambodia",
        "country_code": "855",
        "iso_code": "KH",
        "whatsapp_price": 0.08,
    },
    {
        "id": 37,
        "name": "Cameroon",
        "country_code": "237",
        "iso_code": "CM",
        "whatsapp_price": 0.09,
    },
    {
        "id": 38,
        "name": "Canada",
        "country_code": "1",
        "iso_code": "CA",
        "whatsapp_price": 0.03,
    },
    {
        "id": 39,
        "name": "Cape Verde",
        "country_code": "238",
        "iso_code": "CV",
        "whatsapp_price": 0.06,
    },
    {
        "id": 40,
        "name": "Cayman Islands",
        "country_code": "1345",
        "iso_code": "KY",
        "whatsapp_price": 0.06,
    },
    {
        "id": 41,
        "name": "Central African Republic",
        "country_code": "236",
        "iso_code": "CF",
        "whatsapp_price": 0.06,
    },
    {
        "id": 42,
        "name": "Chad",
        "country_code": "235",
        "iso_code": "TD",
        "whatsapp_price": 0.09,
    },
    {
        "id": 43,
        "name": "Chile",
        "country_code": "56",
        "iso_code": "CL",
        "whatsapp_price": 0.09,
    },
    {
        "id": 44,
        "name": "China",
        "country_code": "86",
        "iso_code": "CN",
        "whatsapp_price": 0.08,
    },
    {
        "id": 45,
        "name": "Christmas Island",
        "country_code": "61",
        "iso_code": "CX",
        "whatsapp_price": 0.06,
    },
    {
        "id": 46,
        "name": "Cocos Islands",
        "country_code": "61",
        "iso_code": "CC",
        "whatsapp_price": 0.06,
    },
    {
        "id": 47,
        "name": "Colombia",
        "country_code": "57",
        "iso_code": "CO",
        "whatsapp_price": 0.03,
    },
    {
        "id": 48,
        "name": "Comoros",
        "country_code": "269",
        "iso_code": "KM",
        "whatsapp_price": 0.06,
    },
    {
        "id": 49,
        "name": "Cook Islands",
        "country_code": "682",
        "iso_code": "CK",
        "whatsapp_price": 0.06,
    },
    {
        "id": 50,
        "name": "Costa Rica",
        "country_code": "506",
        "iso_code": "CR",
        "whatsapp_price": 0.08,
    },
    {
        "id": 51,
        "name": "Croatia",
        "country_code": "385",
        "iso_code": "HR",
        "whatsapp_price": 0.09,
    },
    {
        "id": 52,
        "name": "Cuba",
        "country_code": "53",
        "iso_code": "CU",
        "whatsapp_price": 0.06,
    },
    {
        "id": 53,
        "name": "Curacao",
        "country_code": "599",
        "iso_code": "CW",
        "whatsapp_price": 0.06,
    },
    {
        "id": 54,
        "name": "Cyprus",
        "country_code": "357",
        "iso_code": "CY",
        "whatsapp_price": 0.06,
    },
    {
        "id": 55,
        "name": "Czech Republic",
        "country_code": "420",
        "iso_code": "CZ",
        "whatsapp_price": 0.09,
    },
    {
        "id": 56,
        "name": "Democratic Republic of the Congo",
        "country_code": "243",
        "iso_code": "CD",
        "whatsapp_price": 0.09,
    },
    {
        "id": 57,
        "name": "Denmark",
        "country_code": "45",
        "iso_code": "DK",
        "whatsapp_price": 0.11,
    },
    {
        "id": 58,
        "name": "Djibouti",
        "country_code": "253",
        "iso_code": "DJ",
        "whatsapp_price": 0.06,
    },
    {
        "id": 59,
        "name": "Dominica",
        "country_code": "1767",
        "iso_code": "DM",
        "whatsapp_price": 0.06,
    },
    {
        "id": 60,
        "name": "Dominican Republic",
        "country_code": "1809",
        "iso_code": "DO",
        "whatsapp_price": 0.08,
    },
    {
        "id": 61,
        "name": "East Timor",
        "country_code": "670",
        "iso_code": "TL",
        "whatsapp_price": 0.06,
    },
    {
        "id": 62,
        "name": "Ecuador",
        "country_code": "593",
        "iso_code": "EC",
        "whatsapp_price": 0.08,
    },
    {
        "id": 63,
        "name": "Egypt",
        "country_code": "20",
        "iso_code": "EG",
        "whatsapp_price": 0.10,
    },
    {
        "id": 64,
        "name": "El Salvador",
        "country_code": "503",
        "iso_code": "SV",
        "whatsapp_price": 0.08,
    },
    {
        "id": 65,
        "name": "Equatorial Guinea",
        "country_code": "240",
        "iso_code": "GQ",
        "whatsapp_price": 0.06,
    },
    {
        "id": 66,
        "name": "Eritrea",
        "country_code": "291",
        "iso_code": "ER",
        "whatsapp_price": 0.09,
    },
    {
        "id": 67,
        "name": "Estonia",
        "country_code": "372",
        "iso_code": "EE",
        "whatsapp_price": 0.06,
    },
    {
        "id": 68,
        "name": "Ethiopia",
        "country_code": "251",
        "iso_code": "ET",
        "whatsapp_price": 0.09,
    },
    {
        "id": 69,
        "name": "Falkland Islands",
        "country_code": "500",
        "iso_code": "FK",
        "whatsapp_price": 0.06,
    },
    {
        "id": 70,
        "name": "Faroe Islands",
        "country_code": "298",
        "iso_code": "FO",
        "whatsapp_price": 0.06,
    },
    {
        "id": 71,
        "name": "Fiji",
        "country_code": "679",
        "iso_code": "FJ",
        "whatsapp_price": 0.06,
    },
    {
        "id": 72,
        "name": "Finland",
        "country_code": "358",
        "iso_code": "FI",
        "whatsapp_price": 0.11,
    },
    {
        "id": 73,
        "name": "France",
        "country_code": "33",
        "iso_code": "FR",
        "whatsapp_price": 0.11,
    },
    {
        "id": 74,
        "name": "French Polynesia",
        "country_code": "689",
        "iso_code": "PF",
        "whatsapp_price": 0.06,
    },
    {
        "id": 75,
        "name": "Gabon",
        "country_code": "241",
        "iso_code": "GA",
        "whatsapp_price": 0.09,
    },
    {
        "id": 76,
        "name": "Gambia",
        "country_code": "220",
        "iso_code": "GM",
        "whatsapp_price": 0.09,
    },
    {
        "id": 77,
        "name": "Georgia",
        "country_code": "995",
        "iso_code": "GE",
        "whatsapp_price": 0.09,
    },
    {
        "id": 78,
        "name": "Germany",
        "country_code": "49",
        "iso_code": "DE",
        "whatsapp_price": 0.12,
    },
    {
        "id": 79,
        "name": "Ghana",
        "country_code": "233",
        "iso_code": "GH",
        "whatsapp_price": 0.09,
    },
    {
        "id": 80,
        "name": "Gibraltar",
        "country_code": "350",
        "iso_code": "GI",
        "whatsapp_price": 0.06,
    },
    {
        "id": 81,
        "name": "Greece",
        "country_code": "30",
        "iso_code": "GR",
        "whatsapp_price": 0.09,
    },
    {
        "id": 82,
        "name": "Greenland",
        "country_code": "299",
        "iso_code": "GL",
        "whatsapp_price": 0.06,
    },
    {
        "id": 83,
        "name": "Grenada",
        "country_code": "1473",
        "iso_code": "GD",
        "whatsapp_price": 0.06,
    },
    {
        "id": 84,
        "name": "Guam",
        "country_code": "1671",
        "iso_code": "GU",
        "whatsapp_price": 0.06,
    },
    {
        "id": 85,
        "name": "Guatemala",
        "country_code": "502",
        "iso_code": "GT",
        "whatsapp_price": 0.08,
    },
    {
        "id": 86,
        "name": "Guernsey",
        "country_code": "441481",
        "iso_code": "GG",
        "whatsapp_price": 0.06,
    },
    {
        "id": 87,
        "name": "Guinea",
        "country_code": "224",
        "iso_code": "GN",
        "whatsapp_price": 0.06,
    },
    {
        "id": 88,
        "name": "Guinea-Bissau",
        "country_code": "245",
        "iso_code": "GW",
        "whatsapp_price": 0.09,
    },
    {
        "id": 89,
        "name": "Guyana",
        "country_code": "592",
        "iso_code": "GY",
        "whatsapp_price": 0.06,
    },
    {
        "id": 90,
        "name": "Haiti",
        "country_code": "509",
        "iso_code": "HT",
        "whatsapp_price": 0.08,
    },
    {
        "id": 91,
        "name": "Honduras",
        "country_code": "504",
        "iso_code": "HN",
        "whatsapp_price": 0.08,
    },
    {
        "id": 92,
        "name": "Hong Kong",
        "country_code": "852",
        "iso_code": "HK",
        "whatsapp_price": 0.08,
    },
    {
        "id": 93,
        "name": "Hungary",
        "country_code": "36",
        "iso_code": "HU",
        "whatsapp_price": 0.09,
    },
    {
        "id": 94,
        "name": "Iceland",
        "country_code": "354",
        "iso_code": "IS",
        "whatsapp_price": 0.06,
    },
    {
        "id": 95,
        "name": "India",
        "country_code": "91",
        "iso_code": "IN",
        "whatsapp_price": 0.02,
        "number_of_digits": 12,
    },
    {
        "id": 96,
        "name": "Indonesia",
        "country_code": "62",
        "iso_code": "ID",
        "whatsapp_price": 0.05,
    },
    {
        "id": 97,
        "name": "Iran",
        "country_code": "98",
        "iso_code": "IR",
        "whatsapp_price": 0.06,
    },
    {
        "id": 98,
        "name": "Iraq",
        "country_code": "964",
        "iso_code": "IQ",
        "whatsapp_price": 0.08,
    },
    {
        "id": 99,
        "name": "Ireland",
        "country_code": "353",
        "iso_code": "IE",
        "whatsapp_price": 0.11,
    },
    {
        "id": 100,
        "name": "Isle of Man",
        "country_code": "441624",
        "iso_code": "IM",
        "whatsapp_price": 0.06,
    },
    {
        "id": 101,
        "name": "Israel",
        "country_code": "972",
        "iso_code": "IL",
        "whatsapp_price": 0.05,
    },
    {
        "id": 102,
        "name": "Italy",
        "country_code": "39",
        "iso_code": "IT",
        "whatsapp_price": 0.07,
        "number_of_digits": 12,
    },
    {
        "id": 103,
        "name": "Ivory Coast",
        "country_code": "225",
        "iso_code": "CI",
        "whatsapp_price": 0.09,
    },
    {
        "id": 104,
        "name": "Jamaica",
        "country_code": "1876",
        "iso_code": "JM",
        "whatsapp_price": 0.08,
    },
    {
        "id": 105,
        "name": "Japan",
        "country_code": "81",
        "iso_code": "JP",
        "whatsapp_price": 0.08,
    },
    {
        "id": 106,
        "name": "Jersey",
        "country_code": "441534",
        "iso_code": "JE",
        "whatsapp_price": 0.06,
    },
    {
        "id": 107,
        "name": "Jordan",
        "country_code": "962",
        "iso_code": "JO",
        "whatsapp_price": 0.08,
    },
    {
        "id": 108,
        "name": "Kazakhstan",
        "country_code": "7",
        "iso_code": "KZ",
        "whatsapp_price": 0.06,
    },
    {
        "id": 109,
        "name": "Kenya",
        "country_code": "254",
        "iso_code": "KE",
        "whatsapp_price": 0.09,
    },
    {
        "id": 110,
        "name": "Kiribati",
        "country_code": "686",
        "iso_code": "KI",
        "whatsapp_price": 0.06,
    },
    {
        "id": 111,
        "name": "Kosovo",
        "country_code": "383",
        "iso_code": "XK",
        "whatsapp_price": 0.06,
    },
    {
        "id": 112,
        "name": "Kuwait",
        "country_code": "965",
        "iso_code": "KW",
        "whatsapp_price": 0.08,
    },
    {
        "id": 113,
        "name": "Kyrgyzstan",
        "country_code": "996",
        "iso_code": "KG",
        "whatsapp_price": 0.06,
    },
    {
        "id": 114,
        "name": "Laos",
        "country_code": "856",
        "iso_code": "LA",
        "whatsapp_price": 0.08,
    },
    {
        "id": 115,
        "name": "Latvia",
        "country_code": "371",
        "iso_code": "LV",
        "whatsapp_price": 0.09,
    },
    {
        "id": 116,
        "name": "Lebanon",
        "country_code": "961",
        "iso_code": "LB",
        "whatsapp_price": 0.08,
    },
    {
        "id": 117,
        "name": "Lesotho",
        "country_code": "266",
        "iso_code": "LS",
        "whatsapp_price": 0.09,
    },
    {
        "id": 118,
        "name": "Liberia",
        "country_code": "231",
        "iso_code": "LR",
        "whatsapp_price": 0.09,
    },
    {
        "id": 119,
        "name": "Libya",
        "country_code": "218",
        "iso_code": "LY",
        "whatsapp_price": 0.09,
    },
    {
        "id": 120,
        "name": "Liechtenstein",
        "country_code": "423",
        "iso_code": "LI",
        "whatsapp_price": 0.06,
    },
    {
        "id": 121,
        "name": "Lithuania",
        "country_code": "370",
        "iso_code": "LT",
        "whatsapp_price": 0.09,
    },
    {
        "id": 122,
        "name": "Luxembourg",
        "country_code": "352",
        "iso_code": "LU",
        "whatsapp_price": 0.06,
    },
    {
        "id": 123,
        "name": "Macau",
        "country_code": "853",
        "iso_code": "MO",
        "whatsapp_price": 0.06,
    },
    {
        "id": 124,
        "name": "Macedonia",
        "country_code": "389",
        "iso_code": "MK",
        "whatsapp_price": 0.09,
    },
    {
        "id": 125,
        "name": "Madagascar",
        "country_code": "261",
        "iso_code": "MG",
        "whatsapp_price": 0.09,
    },
    {
        "id": 126,
        "name": "Malawi",
        "country_code": "265",
        "iso_code": "MW",
        "whatsapp_price": 0.09,
    },
    {
        "id": 127,
        "name": "Malaysia",
        "country_code": "60",
        "iso_code": "MY",
        "whatsapp_price": 0.07,
    },
    {
        "id": 128,
        "name": "Maldives",
        "country_code": "960",
        "iso_code": "MV",
        "whatsapp_price": 0.06,
    },
    {
        "id": 129,
        "name": "Mali",
        "country_code": "223",
        "iso_code": "ML",
        "whatsapp_price": 0.09,
    },
    {
        "id": 130,
        "name": "Malta",
        "country_code": "356",
        "iso_code": "MT",
        "whatsapp_price": 0.06,
    },
    {
        "id": 131,
        "name": "Marshall Islands",
        "country_code": "692",
        "iso_code": "MH",
        "whatsapp_price": 0.06,
    },
    {
        "id": 132,
        "name": "Mauritania",
        "country_code": "222",
        "iso_code": "MR",
        "whatsapp_price": 0.09,
    },
    {
        "id": 133,
        "name": "Mauritius",
        "country_code": "230",
        "iso_code": "MU",
        "whatsapp_price": 0.06,
    },
    {
        "id": 134,
        "name": "Mayotte",
        "country_code": "262",
        "iso_code": "YT",
        "whatsapp_price": 0.06,
    },
    {
        "id": 135,
        "name": "Mexico",
        "country_code": "52",
        "iso_code": "MX",
        "whatsapp_price": 0.05,
    },
    {
        "id": 136,
        "name": "Micronesia",
        "country_code": "691",
        "iso_code": "FM",
        "whatsapp_price": 0.06,
    },
    {
        "id": 137,
        "name": "Moldova",
        "country_code": "373",
        "iso_code": "MD",
        "whatsapp_price": 0.09,
    },
    {
        "id": 138,
        "name": "Monaco",
        "country_code": "377",
        "iso_code": "MC",
        "whatsapp_price": 0.06,
    },
    {
        "id": 139,
        "name": "Mongolia",
        "country_code": "976",
        "iso_code": "MN",
        "whatsapp_price": 0.08,
    },
    {
        "id": 140,
        "name": "Montenegro",
        "country_code": "382",
        "iso_code": "ME",
        "whatsapp_price": 0.06,
    },
    {
        "id": 141,
        "name": "Montserrat",
        "country_code": "1664",
        "iso_code": "MS",
        "whatsapp_price": 0.06,
    },
    {
        "id": 142,
        "name": "Morocco",
        "country_code": "212",
        "iso_code": "MA",
        "whatsapp_price": 0.09,
    },
    {
        "id": 143,
        "name": "Mozambique",
        "country_code": "258",
        "iso_code": "MZ",
        "whatsapp_price": 0.09,
    },
    {
        "id": 144,
        "name": "Myanmar",
        "country_code": "95",
        "iso_code": "MM",
        "whatsapp_price": 0.06,
    },
    {
        "id": 145,
        "name": "Namibia",
        "country_code": "264",
        "iso_code": "NA",
        "whatsapp_price": 0.09,
    },
    {
        "id": 146,
        "name": "Nauru",
        "country_code": "674",
        "iso_code": "NR",
        "whatsapp_price": 0.06,
    },
    {
        "id": 147,
        "name": "Nepal",
        "country_code": "977",
        "iso_code": "NP",
        "whatsapp_price": 0.08,
    },
    {
        "id": 148,
        "name": "Netherlands",
        "country_code": "31",
        "iso_code": "NL",
        "whatsapp_price": 0.12,
    },
    {
        "id": 149,
        "name": "Netherlands Antilles",
        "country_code": "599",
        "iso_code": "AN",
        "whatsapp_price": 0.06,
    },
    {
        "id": 150,
        "name": "New Caledonia",
        "country_code": "687",
        "iso_code": "NC",
        "whatsapp_price": 0.06,
    },
    {
        "id": 151,
        "name": "New Zealand",
        "country_code": "64",
        "iso_code": "NZ",
        "whatsapp_price": 0.08,
    },
    {
        "id": 152,
        "name": "Nicaragua",
        "country_code": "505",
        "iso_code": "NI",
        "whatsapp_price": 0.08,
    },
    {
        "id": 153,
        "name": "Niger",
        "country_code": "227",
        "iso_code": "NE",
        "whatsapp_price": 0.09,
    },
    {
        "id": 154,
        "name": "Nigeria",
        "country_code": "234",
        "iso_code": "NG",
        "whatsapp_price": 0.06,
    },
    {
        "id": 155,
        "name": "Niue",
        "country_code": "683",
        "iso_code": "NU",
        "whatsapp_price": 0.06,
    },
    {
        "id": 156,
        "name": "North Korea",
        "country_code": "850",
        "iso_code": "KP",
        "whatsapp_price": 0.06,
    },
    {
        "id": 157,
        "name": "Northern Mariana Islands",
        "country_code": "1670",
        "iso_code": "MP",
        "whatsapp_price": 0.06,
    },
    {
        "id": 158,
        "name": "Norway",
        "country_code": "47",
        "iso_code": "NO",
        "whatsapp_price": 0.11,
    },
    {
        "id": 159,
        "name": "Oman",
        "country_code": "968",
        "iso_code": "OM",
        "whatsapp_price": 0.08,
    },
    {
        "id": 160,
        "name": "Pakistan",
        "country_code": "92",
        "iso_code": "PK",
        "whatsapp_price": 0.05,
    },
    {
        "id": 161,
        "name": "Palau",
        "country_code": "680",
        "iso_code": "PW",
        "whatsapp_price": 0.06,
    },
    {
        "id": 162,
        "name": "Palestine",
        "country_code": "970",
        "iso_code": "PS",
        "whatsapp_price": 0.06,
    },
    {
        "id": 163,
        "name": "Panama",
        "country_code": "507",
        "iso_code": "PA",
        "whatsapp_price": 0.08,
    },
    {
        "id": 164,
        "name": "Papua New Guinea",
        "country_code": "675",
        "iso_code": "PG",
        "whatsapp_price": 0.08,
    },
    {
        "id": 165,
        "name": "Paraguay",
        "country_code": "595",
        "iso_code": "PY",
        "whatsapp_price": 0.08,
    },
    {
        "id": 166,
        "name": "Peru",
        "country_code": "51",
        "iso_code": "PE",
        "whatsapp_price": 0.07,
    },
    {
        "id": 167,
        "name": "Philippines",
        "country_code": "63",
        "iso_code": "PH",
        "whatsapp_price": 0.08,
    },
    {
        "id": 168,
        "name": "Pitcairn",
        "country_code": "64",
        "iso_code": "PN",
        "whatsapp_price": 0.06,
    },
    {
        "id": 169,
        "name": "Poland",
        "country_code": "48",
        "iso_code": "PL",
        "whatsapp_price": 0.09,
    },
    {
        "id": 170,
        "name": "Portugal",
        "country_code": "351",
        "iso_code": "PT",
        "whatsapp_price": 0.11,
    },
    {
        "id": 171,
        "name": "Puerto Rico",
        "country_code": "1787",
        "iso_code": "PR",
        "whatsapp_price": 0.08,
    },
    {
        "id": 172,
        "name": "Qatar",
        "country_code": "974",
        "iso_code": "QA",
        "whatsapp_price": 0.08,
    },
    {
        "id": 173,
        "name": "Republic of the Congo",
        "country_code": "242",
        "iso_code": "CG",
        "whatsapp_price": 0.09,
    },
    {
        "id": 174,
        "name": "Reunion",
        "country_code": "262",
        "iso_code": "RE",
        "whatsapp_price": 0.06,
    },
    {
        "id": 175,
        "name": "Romania",
        "country_code": "40",
        "iso_code": "RO",
        "whatsapp_price": 0.09,
    },
    {
        "id": 176,
        "name": "Russia",
        "country_code": "7",
        "iso_code": "RU",
        "whatsapp_price": 0.08,
    },
    {
        "id": 177,
        "name": "Rwanda",
        "country_code": "250",
        "iso_code": "RW",
        "whatsapp_price": 0.09,
    },
    {
        "id": 178,
        "name": "Saint Barthelemy",
        "country_code": "590",
        "iso_code": "BL",
        "whatsapp_price": 0.06,
    },
    {
        "id": 179,
        "name": "Saint Helena",
        "country_code": "290",
        "iso_code": "SH",
        "whatsapp_price": 0.06,
    },
    {
        "id": 180,
        "name": "Saint Kitts and Nevis",
        "country_code": "1869",
        "iso_code": "KN",
        "whatsapp_price": 0.06,
    },
    {
        "id": 181,
        "name": "Saint Lucia",
        "country_code": "1758",
        "iso_code": "LC",
        "whatsapp_price": 0.06,
    },
    {
        "id": 182,
        "name": "Saint Martin",
        "country_code": "590",
        "iso_code": "MF",
        "whatsapp_price": 0.06,
    },
    {
        "id": 183,
        "name": "Saint Pierre and Miquelon",
        "country_code": "508",
        "iso_code": "PM",
        "whatsapp_price": 0.06,
    },
    {
        "id": 184,
        "name": "Saint Vincent and the Grenadines",
        "country_code": "1784",
        "iso_code": "VC",
        "whatsapp_price": 0.06,
    },
    {
        "id": 185,
        "name": "Samoa",
        "country_code": "685",
        "iso_code": "WS",
        "whatsapp_price": 0.06,
    },
    {
        "id": 186,
        "name": "San Marino",
        "country_code": "378",
        "iso_code": "SM",
        "whatsapp_price": 0.06,
    },
    {
        "id": 187,
        "name": "Sao Tome and Principe",
        "country_code": "239",
        "iso_code": "ST",
        "whatsapp_price": 0.06,
    },
    {
        "id": 188,
        "name": "Saudi Arabia",
        "country_code": "966",
        "iso_code": "SA",
        "whatsapp_price": 0.05,
    },
    {
        "id": 189,
        "name": "Senegal",
        "country_code": "221",
        "iso_code": "SN",
        "whatsapp_price": 0.09,
    },
    {
        "id": 190,
        "name": "Serbia",
        "country_code": "381",
        "iso_code": "RS",
        "whatsapp_price": 0.09,
    },
    {
        "id": 191,
        "name": "Seychelles",
        "country_code": "248",
        "iso_code": "SC",
        "whatsapp_price": 0.06,
    },
    {
        "id": 192,
        "name": "Sierra Leone",
        "country_code": "232",
        "iso_code": "SL",
        "whatsapp_price": 0.09,
    },
    {
        "id": 193,
        "name": "Singapore",
        "country_code": "65",
        "iso_code": "SG",
        "whatsapp_price": 0.08,
    },
    {
        "id": 194,
        "name": "Sint Maarten",
        "country_code": "1721",
        "iso_code": "SX",
        "whatsapp_price": 0.06,
    },
    {
        "id": 195,
        "name": "Slovakia",
        "country_code": "421",
        "iso_code": "SK",
        "whatsapp_price": 0.09,
    },
    {
        "id": 196,
        "name": "Slovenia",
        "country_code": "386",
        "iso_code": "SI",
        "whatsapp_price": 0.09,
    },
    {
        "id": 197,
        "name": "Solomon Islands",
        "country_code": "677",
        "iso_code": "SB",
        "whatsapp_price": 0.06,
    },
    {
        "id": 198,
        "name": "Somalia",
        "country_code": "252",
        "iso_code": "SO",
        "whatsapp_price": 0.09,
    },
    {
        "id": 199,
        "name": "South Africa",
        "country_code": "27",
        "iso_code": "ZA",
        "whatsapp_price": 0.04,
    },
    {
        "id": 200,
        "name": "South Korea",
        "country_code": "82",
        "iso_code": "KR",
        "whatsapp_price": 0.06,
    },
    {
        "id": 201,
        "name": "South Sudan",
        "country_code": "211",
        "iso_code": "SS",
        "whatsapp_price": 0.09,
    },
    {
        "id": 202,
        "name": "Spain",
        "country_code": "34",
        "iso_code": "ES",
        "whatsapp_price": 0.06,
    },
    {
        "id": 203,
        "name": "Sri Lanka",
        "country_code": "94",
        "iso_code": "LK",
        "whatsapp_price": 0.08,
    },
    {
        "id": 204,
        "name": "Sudan",
        "country_code": "249",
        "iso_code": "SD",
        "whatsapp_price": 0.09,
    },
    {
        "id": 205,
        "name": "Suriname",
        "country_code": "597",
        "iso_code": "SR",
        "whatsapp_price": 0.06,
    },
    {
        "id": 206,
        "name": "Svalbard and Jan Mayen",
        "country_code": "47",
        "iso_code": "SJ",
        "whatsapp_price": 0.06,
    },
    {
        "id": 207,
        "name": "Swaziland",
        "country_code": "268",
        "iso_code": "SZ",
        "whatsapp_price": 0.09,
    },
    {
        "id": 208,
        "name": "Sweden",
        "country_code": "46",
        "iso_code": "SE",
        "whatsapp_price": 0.11,
    },
    {
        "id": 209,
        "name": "Switzerland",
        "country_code": "41",
        "iso_code": "CH",
        "whatsapp_price": 0.11,
    },
    {
        "id": 210,
        "name": "Syria",
        "country_code": "963",
        "iso_code": "SY",
        "whatsapp_price": 0.06,
    },
    {
        "id": 211,
        "name": "Taiwan",
        "country_code": "886",
        "iso_code": "TW",
        "whatsapp_price": 0.08,
    },
    {
        "id": 212,
        "name": "Tajikistan",
        "country_code": "992",
        "iso_code": "TJ",
        "whatsapp_price": 0.08,
    },
    {
        "id": 213,
        "name": "Tanzania",
        "country_code": "255",
        "iso_code": "TZ",
        "whatsapp_price": 0.09,
    },
    {
        "id": 214,
        "name": "Thailand",
        "country_code": "66",
        "iso_code": "TH",
        "whatsapp_price": 0.08,
    },
    {
        "id": 215,
        "name": "Togo",
        "country_code": "228",
        "iso_code": "TG",
        "whatsapp_price": 0.09,
    },
    {
        "id": 216,
        "name": "Tokelau",
        "country_code": "690",
        "iso_code": "TK",
        "whatsapp_price": 0.06,
    },
    {
        "id": 217,
        "name": "Tonga",
        "country_code": "676",
        "iso_code": "TO",
        "whatsapp_price": 0.06,
    },
    {
        "id": 218,
        "name": "Trinidad and Tobago",
        "country_code": "1868",
        "iso_code": "TT",
        "whatsapp_price": 0.06,
    },
    {
        "id": 219,
        "name": "Tunisia",
        "country_code": "216",
        "iso_code": "TN",
        "whatsapp_price": 0.09,
    },
    {
        "id": 220,
        "name": "Turkey",
        "country_code": "90",
        "iso_code": "TR",
        "whatsapp_price": 0.03,
    },
    {
        "id": 221,
        "name": "Turkmenistan",
        "country_code": "993",
        "iso_code": "TM",
        "whatsapp_price": 0.08,
    },
    {
        "id": 222,
        "name": "Turks and Caicos Islands",
        "country_code": "1649",
        "iso_code": "TC",
        "whatsapp_price": 0.06,
    },
    {
        "id": 223,
        "name": "Tuvalu",
        "country_code": "688",
        "iso_code": "TV",
        "whatsapp_price": 0.06,
    },
    {
        "id": 224,
        "name": "U.S. Virgin Islands",
        "country_code": "1340",
        "iso_code": "VI",
        "whatsapp_price": 0.06,
    },
    {
        "id": 225,
        "name": "Uganda",
        "country_code": "256",
        "iso_code": "UG",
        "whatsapp_price": 0.09,
    },
    {
        "id": 226,
        "name": "Ukraine",
        "country_code": "380",
        "iso_code": "UA",
        "whatsapp_price": 0.09,
    },
    {
        "id": 227,
        "name": "United Arab Emirates",
        "country_code": "971",
        "iso_code": "AE",
        "whatsapp_price": 0.05,
    },
    {
        "id": 228,
        "name": "United Kingdom",
        "country_code": "44",
        "iso_code": "GB",
        "whatsapp_price": 0.07,
    },
    {
        "id": 229,
        "name": "United States",
        "country_code": "1",
        "iso_code": "US",
        "whatsapp_price": 0.03,
    },
    {
        "id": 230,
        "name": "Uruguay",
        "country_code": "598",
        "iso_code": "UY",
        "whatsapp_price": 0.08,
    },
    {
        "id": 231,
        "name": "Uzbekistan",
        "country_code": "998",
        "iso_code": "UZ",
        "whatsapp_price": 0.08,
    },
    {
        "id": 232,
        "name": "Vanuatu",
        "country_code": "678",
        "iso_code": "VU",
        "whatsapp_price": 0.06,
    },
    {
        "id": 233,
        "name": "Vatican",
        "country_code": "379",
        "iso_code": "VA",
        "whatsapp_price": 0.06,
    },
    {
        "id": 234,
        "name": "Venezuela",
        "country_code": "58",
        "iso_code": "VE",
        "whatsapp_price": 0.08,
    },
    {
        "id": 235,
        "name": "Vietnam",
        "country_code": "84",
        "iso_code": "VN",
        "whatsapp_price": 0.08,
    },
    {
        "id": 236,
        "name": "Wallis and Futuna",
        "country_code": "681",
        "iso_code": "WF",
        "whatsapp_price": 0.06,
    },
    {
        "id": 237,
        "name": "Western Sahara",
        "country_code": "212",
        "iso_code": "EH",
        "whatsapp_price": 0.06,
    },
    {
        "id": 238,
        "name": "Yemen",
        "country_code": "967",
        "iso_code": "YE",
        "whatsapp_price": 0.08,
    },
    {
        "id": 239,
        "name": "Zambia",
        "country_code": "260",
        "iso_code": "ZM",
        "whatsapp_price": 0.09,
    },
    {
        "id": 240,
        "name": "Zimbabwe",
        "country_code": "263",
        "iso_code": "ZW",
        "whatsapp_price": 0.06,
    },
    {
        "id": 241,
        "name": "Guadeloupe",
        "country_code": "590",
        "iso_code": "GP",
        "whatsapp_price": 0.06,
    },
    {
        "id": 242,
        "name": "Martinique",
        "country_code": "596",
        "iso_code": "MQ",
        "whatsapp_price": 0.06,
    },
    {
        "id": 243,
        "name": "Bonaire, Sint Eustatius and Saba",
        "country_code": "599",
        "iso_code": "BQ",
        "whatsapp_price": 0.06,
    },
    {
        "id": 244,
        "name": "French Guiana",
        "country_code": "594",
        "iso_code": "GF",
        "whatsapp_price": 0.06,
    },
    {
        "id": 245,
        "name": "United States Minor",
        "country_code": "246",
        "iso_code": "UM",
        "whatsapp_price": 0.06,
    },
    {
        "id": 246,
        "name": "French Southern and Antarctic Lands",
        "country_code": "262",
        "iso_code": "TF",
        "whatsapp_price": 0.06,
    },
    {
        "id": 249,
        "name": "Aland Islands",
        "country_code": "358",
        "iso_code": "AX",
        "whatsapp_price": 0.06,
    },
    {
        "id": 255,
        "name": "Norfolk Island",
        "country_code": "672",
        "iso_code": "NF",
        "whatsapp_price": 0.06,
    },
    {
        "id": 256,
        "name": "Bouvet Island",
        "country_code": "47",
        "iso_code": "BV",
        "whatsapp_price": 0.06,
    },
]
